import nock from 'nock';

import { OpenWeatherMapApiClient, } from './OpenWeatherMapApiClient';

const latitude  = 22.3080;
const longitude = 113.9185;
const hours     = 8;
const days      = 4;
const locale    = 'en';
const apiKey    = process.env.REACT_APP_OPEN_WEATHER_MAP_API_KEY;

const weatherResponse = {
    'lat'             : 22.31,
    'lon'             : 113.92,
    'timezone'        : 'Asia/Hong_Kong',
    'timezone_offset' : 28800,
    'current'         : {
        'dt'         : 1600682660,
        'sunrise'    : 1600639967,
        'sunset'     : 1600683726,
        'temp'       : 28.01,
        'feels_like' : 28.45,
        'pressure'   : 1009,
        'humidity'   : 79,
        'dew_point'  : 24.03,
        'uvi'        : 10.64,
        'clouds'     : 40,
        'visibility' : 10000,
        'wind_speed' : 7.7,
        'wind_deg'   : 100,
        'weather'    : [
            {
                'id'          : 500,
                'main'        : 'Rain',
                'description' : 'light rain',
                'icon'        : '10d',
            },
        ],
        'rain'       : {
            '1h' : 0.26,
        }
    },
    'hourly'          : [
        {
            'dt'         : 1600682400,
            'temp'       : 28.01,
            'feels_like' : 28.87,
            'pressure'   : 1009,
            'humidity'   : 79,
            'dew_point'  : 24.03,
            'clouds'     : 40,
            'visibility' : 10000,
            'wind_speed' : 7.1,
            'wind_deg'   : 124,
            'weather'    : [
                {
                    'id'          : 500,
                    'main'        : 'Rain',
                    'description' : 'light rain',
                    'icon'        : '10d',
                },
            ],
            'pop'        : 0.53,
            'rain'       : {
                '1h' : 0.37,
            },
        }, {
            'dt'         : 1600686000,
            'temp'       : 28.16,
            'feels_like' : 29.12,
            'pressure'   : 1009,
            'humidity'   : 80,
            'dew_point'  : 24.38,
            'clouds'     : 69,
            'visibility' : 10000,
            'wind_speed' : 7.25,
            'wind_deg'   : 118,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0.77
        }, {
            'dt'         : 1600689600,
            'temp'       : 28.15,
            'feels_like' : 29.22,
            'pressure'   : 1010,
            'humidity'   : 82,
            'dew_point'  : 24.78,
            'clouds'     : 87,
            'visibility' : 10000,
            'wind_speed' : 7.45,
            'wind_deg'   : 118,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0.8,
        }, {
            'dt'         : 1600693200,
            'temp'       : 28.23,
            'feels_like' : 29.3,
            'pressure'   : 1011,
            'humidity'   : 81,
            'dew_point'  : 24.66,
            'clouds'     : 96,
            'visibility' : 10000,
            'wind_speed' : 7.34,
            'wind_deg'   : 116,
            'weather'    : [
                {
                    'id'          : 500,
                    'main'        : 'Rain',
                    'description' : 'light rain',
                    'icon'        : '10n',
                },
            ],
            'pop'        : 0.66,
            'rain'       : {
                '1h' : 0.3,
            },
        }, {
            'dt'         : 1600696800,
            'temp'       : 28.18,
            'feels_like' : 29.19,
            'pressure'   : 1012,
            'humidity'   : 81,
            'dew_point'  : 24.61,
            'clouds'     : 100,
            'visibility' : 10000,
            'wind_speed' : 7.38,
            'wind_deg'   : 112,
            'weather'    : [
                {
                    'id'          : 500,
                    'main'        : 'Rain',
                    'description' : 'light rain',
                    'icon'        : '10n',
                },
            ],
            'pop'        : 0.7,
            'rain'       : {
                '1h' : 0.71,
            },
        }, {
            'dt'         : 1600700400,
            'temp'       : 28.13,
            'feels_like' : 29.03,
            'pressure'   : 1012,
            'humidity'   : 81,
            'dew_point'  : 24.68,
            'clouds'     : 100,
            'visibility' : 10000,
            'wind_speed' : 7.5,
            'wind_deg'   : 110,
            'weather'    : [
                {
                    'id'          : 500,
                    'main'        : 'Rain',
                    'description' : 'light rain',
                    'icon'        : '10n',
                },
            ],
            'pop'        : 0.7,
            'rain'       : {
                '1h' : 0.84,
            },
        }, {
            'dt'         : 1600704000,
            'temp'       : 28.05,
            'feels_like' : 28.92,
            'pressure'   : 1012,
            'humidity'   : 81,
            'dew_point'  : 24.58,
            'clouds'     : 100,
            'visibility' : 10000,
            'wind_speed' : 7.47,
            'wind_deg'   : 108,
            'weather'    : [
                {
                    'id'          : 500,
                    'main'        : 'Rain',
                    'description' : 'light rain',
                    'icon'        : '10n',
                },
            ],
            'pop'        : 0.7,
            'rain'       : {
                '1h' : 0.75,
            },
        }, {
            'dt'         : 1600707600,
            'temp'       : 27.87,
            'feels_like' : 28.65,
            'pressure'   : 1011,
            'humidity'   : 81,
            'dew_point'  : 24.51,
            'clouds'     : 100,
            'visibility' : 10000,
            'wind_speed' : 7.45,
            'wind_deg'   : 104,
            'weather'    : [
                {
                    'id'          : 500,
                    'main'        : 'Rain',
                    'description' : 'light rain',
                    'icon'        : '10n',
                },
            ],
            'pop'        : 0.71,
            'rain'       : {
                '1h' : 0.73,
            },
        }, {
            'dt'         : 1600711200,
            'temp'       : 27.61,
            'feels_like' : 28.31,
            'pressure'   : 1011,
            'humidity'   : 82,
            'dew_point'  : 24.45,
            'clouds'     : 100,
            'visibility' : 10000,
            'wind_speed' : 7.52,
            'wind_deg'   : 102,
            'weather'    : [
                {
                    'id'          : 500,
                    'main'        : 'Rain',
                    'description' : 'light rain',
                    'icon'        : '10n',
                },
            ],
            'pop'        : 0.66,
            'rain'       : {
                '1h' : 0.58,
            },
        }, {
            'dt'         : 1600714800,
            'temp'       : 27.55,
            'feels_like' : 28.13,
            'pressure'   : 1010,
            'humidity'   : 82,
            'dew_point'  : 24.37,
            'clouds'     : 96,
            'visibility' : 10000,
            'wind_speed' : 7.64,
            'wind_deg'   : 98,
            'weather'    : [
                {
                    'id'          : 500,
                    'main'        : 'Rain',
                    'description' : 'light rain',
                    'icon'        : '10n',
                },
            ],
            'pop'        : 0.35,
            'rain'       : {
                '1h' : 0.11,
            },
        }, {
            'dt'         : 1600718400,
            'temp'       : 27.6,
            'feels_like' : 27.95,
            'pressure'   : 1010,
            'humidity'   : 81,
            'dew_point'  : 24.2,
            'clouds'     : 94,
            'visibility' : 10000,
            'wind_speed' : 7.84,
            'wind_deg'   : 97,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0.31,
        }, {
            'dt'         : 1600722000,
            'temp'       : 27.61,
            'feels_like' : 27.68,
            'pressure'   : 1010,
            'humidity'   : 80,
            'dew_point'  : 24.04,
            'clouds'     : 83,
            'visibility' : 10000,
            'wind_speed' : 8.08,
            'wind_deg'   : 96,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0.33,
        }, {
            'dt'         : 1600725600,
            'temp'       : 27.52,
            'feels_like' : 27.65,
            'pressure'   : 1011,
            'humidity'   : 80,
            'dew_point'  : 23.92,
            'clouds'     : 81,
            'visibility' : 10000,
            'wind_speed' : 7.92,
            'wind_deg'   : 94,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0.25,
        }, {
            'dt'         : 1600729200,
            'temp'       : 27.43,
            'feels_like' : 27.41,
            'pressure'   : 1011,
            'humidity'   : 80,
            'dew_point'  : 23.83,
            'clouds'     : 84,
            'visibility' : 10000,
            'wind_speed' : 8.06,
            'wind_deg'   : 92,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.25,
        }, {
            'dt'         : 1600732800,
            'temp'       : 27.58,
            'feels_like' : 27.7,
            'pressure'   : 1011,
            'humidity'   : 79,
            'dew_point'  : 23.8,
            'clouds'     : 83,
            'visibility' : 10000,
            'wind_speed' : 7.81,
            'wind_deg'   : 92,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.25,
        }, {
            'dt'         : 1600736400,
            'temp'       : 27.9,
            'feels_like' : 28.35,
            'pressure'   : 1011,
            'humidity'   : 78,
            'dew_point'  : 23.77,
            'clouds'     : 99,
            'visibility' : 10000,
            'wind_speed' : 7.41,
            'wind_deg'   : 93,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.02,
        }, {
            'dt'         : 1600740000,
            'temp'       : 28.16,
            'feels_like' : 28.62,
            'pressure'   : 1011,
            'humidity'   : 77,
            'dew_point'  : 23.78,
            'clouds'     : 85,
            'visibility' : 10000,
            'wind_speed' : 7.43,
            'wind_deg'   : 96,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.02,
        }, {
            'dt'         : 1600743600,
            'temp'       : 28.25,
            'feels_like' : 28.47,
            'pressure'   : 1011,
            'humidity'   : 76,
            'dew_point'  : 23.82,
            'clouds'     : 76,
            'visibility' : 10000,
            'wind_speed' : 7.67,
            'wind_deg'   : 99,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.02,
        }, {
            'dt'         : 1600747200,
            'temp'       : 28.28,
            'feels_like' : 28.42,
            'pressure'   : 1011,
            'humidity'   : 76,
            'dew_point'  : 23.84,
            'clouds'     : 82,
            'visibility' : 10000,
            'wind_speed' : 7.8,
            'wind_deg'   : 100,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.01,
        }, {
            'dt'         : 1600750800,
            'temp'       : 28.19,
            'feels_like' : 28.29,
            'pressure'   : 1010,
            'humidity'   : 77,
            'dew_point'  : 23.96,
            'clouds'     : 86,
            'visibility' : 10000,
            'wind_speed' : 7.97,
            'wind_deg'   : 102,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.01,
        }, {
            'dt'         : 1600754400,
            'temp'       : 28.18,
            'feels_like' : 28.21,
            'pressure'   : 1009,
            'humidity'   : 78,
            'dew_point'  : 24,
            'clouds'     : 88,
            'visibility' : 10000,
            'wind_speed' : 8.24,
            'wind_deg'   : 103,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.01,
        }, {
            'dt'         : 1600758000,
            'temp'       : 28.21,
            'feels_like' : 28.19,
            'pressure'   : 1008,
            'humidity'   : 77,
            'dew_point'  : 23.91,
            'clouds'     : 81,
            'visibility' : 10000,
            'wind_speed' : 8.16,
            'wind_deg'   : 106,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600761600,
            'temp'       : 28.04,
            'feels_like' : 28.08,
            'pressure'   : 1008,
            'humidity'   : 78,
            'dew_point'  : 23.87,
            'clouds'     : 53,
            'visibility' : 10000,
            'wind_speed' : 8.12,
            'wind_deg'   : 108,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600765200,
            'temp'       : 27.81,
            'feels_like' : 27.81,
            'pressure'   : 1008,
            'humidity'   : 79,
            'dew_point'  : 23.84,
            'clouds'     : 68,
            'visibility' : 10000,
            'wind_speed' : 8.16,
            'wind_deg'   : 108,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600768800,
            'temp'       : 27.68,
            'feels_like' : 27.67,
            'pressure'   : 1008,
            'humidity'   : 79,
            'dew_point'  : 23.9,
            'clouds'     : 69,
            'visibility' : 10000,
            'wind_speed' : 8.07,
            'wind_deg'   : 108,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600772400,
            'temp'       : 27.66,
            'feels_like' : 27.9,
            'pressure'   : 1009,
            'humidity'   : 80,
            'dew_point'  : 24.01,
            'clouds'     : 73,
            'visibility' : 10000,
            'wind_speed' : 7.88,
            'wind_deg'   : 108,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600776000,
            'temp'       : 27.68,
            'feels_like' : 28.11,
            'pressure'   : 1009,
            'humidity'   : 80,
            'dew_point'  : 23.93,
            'clouds'     : 78,
            'visibility' : 10000,
            'wind_speed' : 7.62,
            'wind_deg'   : 109,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600779600,
            'temp'       : 27.68,
            'feels_like' : 28.1,
            'pressure'   : 1010,
            'humidity'   : 80,
            'dew_point'  : 23.94,
            'clouds'     : 100,
            'visibility' : 10000,
            'wind_speed' : 7.63,
            'wind_deg'   : 109,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600783200,
            'temp'       : 27.66,
            'feels_like' : 28.25,
            'pressure'   : 1011,
            'humidity'   : 80,
            'dew_point'  : 23.99,
            'clouds'     : 100,
            'visibility' : 10000,
            'wind_speed' : 7.38,
            'wind_deg'   : 110,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600786800,
            'temp'       : 27.73,
            'feels_like' : 28.45,
            'pressure'   : 1011,
            'humidity'   : 80,
            'dew_point'  : 23.98,
            'clouds'     : 100,
            'visibility' : 10000,
            'wind_speed' : 7.24,
            'wind_deg'   : 110,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600790400,
            'temp'       : 27.82,
            'feels_like' : 28.48,
            'pressure'   : 1011,
            'humidity'   : 78,
            'dew_point'  : 23.82,
            'clouds'     : 100,
            'visibility' : 10000,
            'wind_speed' : 7.05,
            'wind_deg'   : 108,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600794000,
            'temp'       : 27.71,
            'feels_like' : 28.57,
            'pressure'   : 1010,
            'humidity'   : 79,
            'dew_point'  : 23.81,
            'clouds'     : 100,
            'visibility' : 10000,
            'wind_speed' : 6.85,
            'wind_deg'   : 106,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600797600,
            'temp'       : 27.58,
            'feels_like' : 28.5,
            'pressure'   : 1010,
            'humidity'   : 79,
            'dew_point'  : 23.77,
            'clouds'     : 99,
            'visibility' : 10000,
            'wind_speed' : 6.66,
            'wind_deg'   : 102,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600801200,
            'temp'       : 27.44,
            'feels_like' : 28.41,
            'pressure'   : 1009,
            'humidity'   : 80,
            'dew_point'  : 23.68,
            'clouds'     : 100,
            'visibility' : 10000,
            'wind_speed' : 6.66,
            'wind_deg'   : 99,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0.01,
        }, {
            'dt'         : 1600804800,
            'temp'       : 27.39,
            'feels_like' : 28.15,
            'pressure'   : 1009,
            'humidity'   : 79,
            'dew_point'  : 23.61,
            'clouds'     : 99,
            'visibility' : 10000,
            'wind_speed' : 6.74,
            'wind_deg'   : 97,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0.01,
        }, {
            'dt'         : 1600808400,
            'temp'       : 27.44,
            'feels_like' : 27.96,
            'pressure'   : 1010,
            'humidity'   : 79,
            'dew_point'  : 23.57,
            'clouds'     : 85,
            'visibility' : 10000,
            'wind_speed' : 7.12,
            'wind_deg'   : 98,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0.01,
        }, {
            'dt'         : 1600812000,
            'temp'       : 27.47,
            'feels_like' : 27.98,
            'pressure'   : 1010,
            'humidity'   : 79,
            'dew_point'  : 23.58,
            'clouds'     : 82,
            'visibility' : 10000,
            'wind_speed' : 7.16,
            'wind_deg'   : 101,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04n',
                },
            ],
            'pop'        : 0.01,
        }, {
            'dt'         : 1600815600,
            'temp'       : 27.58,
            'feels_like' : 28.14,
            'pressure'   : 1011,
            'humidity'   : 79,
            'dew_point'  : 23.62,
            'clouds'     : 81,
            'visibility' : 10000,
            'wind_speed' : 7.18,
            'wind_deg'   : 98,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.01,
        }, {
            'dt'         : 1600819200,
            'temp'       : 27.57,
            'feels_like' : 27.97,
            'pressure'   : 1011,
            'humidity'   : 79,
            'dew_point'  : 23.68,
            'clouds'     : 83,
            'visibility' : 10000,
            'wind_speed' : 7.4,
            'wind_deg'   : 91,
            'weather'    : [
                {
                    'id'          : 803,
                    'main'        : 'Clouds',
                    'description' : 'broken clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.01,
        }, {
            'dt'         : 1600822800,
            'temp'       : 27.57,
            'feels_like' : 27.9,
            'pressure'   : 1011,
            'humidity'   : 78,
            'dew_point'  : 23.58,
            'clouds'     : 94,
            'visibility' : 10000,
            'wind_speed' : 7.33,
            'wind_deg'   : 90,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.08,
        }, {
            'dt'         : 1600826400,
            'temp'       : 27.81,
            'feels_like' : 28.39,
            'pressure'   : 1012,
            'humidity'   : 77,
            'dew_point'  : 23.46,
            'clouds'     : 96,
            'visibility' : 10000,
            'wind_speed' : 6.99,
            'wind_deg'   : 96,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.05,
        }, {
            'dt'         : 1600830000,
            'temp'       : 28.06,
            'feels_like' : 28.37,
            'pressure'   : 1011,
            'humidity'   : 75,
            'dew_point'  : 23.42,
            'clouds'     : 95,
            'visibility' : 10000,
            'wind_speed' : 7.21,
            'wind_deg'   : 99,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.04,
        }, {
            'dt'         : 1600833600,
            'temp'       : 28.22,
            'feels_like' : 28.7,
            'pressure'   : 1011,
            'humidity'   : 74,
            'dew_point'  : 23.35,
            'clouds'     : 95,
            'visibility' : 10000,
            'wind_speed' : 6.91,
            'wind_deg'   : 103,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.04,
        }, {
            'dt'         : 1600837200,
            'temp'       : 28.28,
            'feels_like' : 29.07,
            'pressure'   : 1010,
            'humidity'   : 74,
            'dew_point'  : 23.31,
            'clouds'     : 91,
            'visibility' : 10000,
            'wind_speed' : 6.52,
            'wind_deg'   : 106,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.01,
        }, {
            'dt'         : 1600840800,
            'temp'       : 28.34,
            'feels_like' : 29.18,
            'pressure'   : 1009,
            'humidity'   : 74,
            'dew_point'  : 23.38,
            'clouds'     : 89,
            'visibility' : 10000,
            'wind_speed' : 6.49,
            'wind_deg'   : 106,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0.01,
        }, {
            'dt'         : 1600844400,
            'temp'       : 28.35,
            'feels_like' : 29.23,
            'pressure'   : 1009,
            'humidity'   : 75,
            'dew_point'  : 23.54,
            'clouds'     : 93,
            'visibility' : 10000,
            'wind_speed' : 6.62,
            'wind_deg'   : 109,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600848000,
            'temp'       : 28.25,
            'feels_like' : 29.08,
            'pressure'   : 1008,
            'humidity'   : 75,
            'dew_point'  : 23.58,
            'clouds'     : 87,
            'visibility' : 10000,
            'wind_speed' : 6.62,
            'wind_deg'   : 109,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0,
        }, {
            'dt'         : 1600851600,
            'temp'       : 28.07,
            'feels_like' : 28.71,
            'pressure'   : 1009,
            'humidity'   : 76,
            'dew_point'  : 23.58,
            'clouds'     : 85,
            'visibility' : 10000,
            'wind_speed' : 6.93,
            'wind_deg'   : 105,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'pop'        : 0,
        },
    ],
    'daily'           : [
        {
            'dt'         : 1600660800,
            'sunrise'    : 1600639967,
            'sunset'     : 1600683726,
            'temp'       : {
                'day'   : 29.02,
                'min'   : 28.01,
                'max'   : 29.02,
                'night' : 28.1,
                'eve'   : 28.01,
                'morn'  : 28.51,
            },
            'feels_like' : {
                'day'   : 30.66,
                'night' : 28.98,
                'eve'   : 28.75,
                'morn'  : 30.88,
            },
            'pressure'   : 1012,
            'humidity'   : 76,
            'dew_point'  : 24.53,
            'wind_speed' : 6.26,
            'wind_deg'   : 105,
            'weather'    : [
                {
                    'id'          : 501,
                    'main'        : 'Rain',
                    'description' : 'moderate rain',
                    'icon'        : '10d',
                },
            ],
            'clouds'     : 97,
            'pop'        : 0.93,
            'rain'       : 5.21,
            'uvi'        : 10.64,
        }, {
            'dt'         : 1600747200,
            'sunrise'    : 1600726383,
            'sunset'     : 1600770065,
            'temp'       : {
                'day'   : 28.25,
                'min'   : 27.58,
                'max'   : 28.25,
                'night' : 27.73,
                'eve'   : 27.81,
                'morn'  : 27.61,
            },
            'feels_like' : {
                'day'   : 28.47,
                'night' : 28.45,
                'eve'   : 27.81,
                'morn'  : 27.68,
            },
            'pressure'   : 1011,
            'humidity'   : 76,
            'dew_point'  : 23.82,
            'wind_speed' : 7.67,
            'wind_deg'   : 99,
            'weather'    : [
                {
                    'id'          : 500,
                    'main'        : 'Rain',
                    'description' : 'light rain',
                    'icon'        : '10d',
                },
            ],
            'clouds'     : 76,
            'pop'        : 0.66,
            'rain'       : 2.23,
            'uvi'        : 11.31,
        }, {
            'dt'         : 1600833600,
            'sunrise'    : 1600812799,
            'sunset'     : 1600856405,
            'temp'       : {
                'day'   : 28.06,
                'min'   : 27.44,
                'max'   : 28.34,
                'night' : 27.63,
                'eve'   : 28.07,
                'morn'  : 27.44,
            },
            'feels_like' : {
                'day'   : 28.37,
                'night' : 29.25,
                'eve'   : 28.71,
                'morn'  : 27.96,
            },
            'pressure'   : 1011,
            'humidity'   : 75,
            'dew_point'  : 23.42,
            'wind_speed' : 7.21,
            'wind_deg'   : 99,
            'weather'    : [
                {
                    'id'          : 804,
                    'main'        : 'Clouds',
                    'description' : 'overcast clouds',
                    'icon'        : '04d',
                },
            ],
            'clouds'     : 95,
            'pop'        : 0.26,
            'uvi'        : 12.76,
        }, {
            'dt'         : 1600920000,
            'sunrise'    : 1600899216,
            'sunset'     : 1600942745,
            'temp'       : {
                'day'   : 28.08,
                'min'   : 27.45,
                'max'   : 28.38,
                'night' : 27.57,
                'eve'   : 28.31,
                'morn'  : 27.51,
            },
            'feels_like' : {
                'day'   : 31.15,
                'night' : 29.3,
                'eve'   : 31.17,
                'morn'  : 29.97,
            },
            'pressure'   : 1012,
            'humidity'   : 76,
            'dew_point'  : 23.6,
            'wind_speed' : 3.46,
            'wind_deg'   : 89,
            'weather'    : [
                {
                    'id'          : 502,
                    'main'        : 'Rain',
                    'description' : 'heavy intensity rain',
                    'icon'        : '10d',
                },
            ],
            'clouds'     : 99,
            'pop'        : 0.86,
            'rain'       : 13.96,
            'uvi'        : 11.28,
        }, {
            'dt'         : 1601006400,
            'sunrise'    : 1600985633,
            'sunset'     : 1601029085,
            'temp'       : {
                'day'   : 27.43,
                'min'   : 26.53,
                'max'   : 27.65,
                'night' : 27.21,
                'eve'   : 27.61,
                'morn'  : 26.53,
            },
            'feels_like' : {
                'day'   : 29.5,
                'night' : 26.49,
                'eve'   : 27.63,
                'morn'  : 28.88,
            },
            'pressure'   : 1011,
            'humidity'   : 74,
            'dew_point'  : 22.42,
            'wind_speed' : 4.05,
            'wind_deg'   : 94,
            'weather'    : [
                {
                    'id'          : 501,
                    'main'        : 'Rain',
                    'description' : 'moderate rain',
                    'icon'        : '10d',
                },
            ],
            'clouds'     : 100,
            'pop'        : 0.87,
            'rain'       : 3.41,
            'uvi'        : 11.27,
        }, {
            'dt'         : 1601092800,
            'sunrise'    : 1601072050,
            'sunset'     : 1601115425,
            'temp'       : {
                'day'   : 27.05,
                'min'   : 26.89,
                'max'   : 27.51,
                'night' : 27.12,
                'eve'   : 27.33,
                'morn'  : 26.92,
            },
            'feels_like' : {
                'day'   : 25.48,
                'night' : 24.93,
                'eve'   : 26.05,
                'morn'  : 25.57,
            },
            'pressure'   : 1011,
            'humidity'   : 78,
            'dew_point'  : 22.92,
            'wind_speed' : 9.64,
            'wind_deg'   : 96,
            'weather'    : [
                {
                    'id'          : 500,
                    'main'        : 'Rain',
                    'description' : 'light rain',
                    'icon'        : '10d',
                },
            ],
            'clouds'     : 100,
            'pop'        : 0.82,
            'rain'       : 2.42,
            'uvi'        : 11.22,
        }, {
            'dt'         : 1601179200,
            'sunrise'    : 1601158467,
            'sunset'     : 1601201766,
            'temp'       : {
                'day'   : 27.12,
                'min'   : 26.76,
                'max'   : 27.62,
                'night' : 26.87,
                'eve'   : 27.62,
                'morn'  : 26.76,
            },
            'feels_like' : {
                'day'   : 26.32,
                'night' : 25.12,
                'eve'   : 26.36,
                'morn'  : 24.87,
            },
            'pressure'   : 1012,
            'humidity'   : 76,
            'dew_point'  : 22.74,
            'wind_speed' : 8.25,
            'wind_deg'   : 78,
            'weather'    : [
                {
                    'id'          : 500,
                    'main'        : 'Rain',
                    'description' : 'light rain',
                    'icon'        : '10d',
                },
            ],
            'clouds'     : 100,
            'pop'        : 0.63,
            'rain'       : 1.05,
            'uvi'        : 11.55,
        }, {
            'dt'         : 1601265600,
            'sunrise'    : 1601244884,
            'sunset'     : 1601288106,
            'temp'       : {
                'day'   : 25.7,
                'min'   : 25.7,
                'max'   : 27.45,
                'night' : 27.45,
                'eve'   : 27.23,
                'morn'  : 26.79,
            },
            'feels_like' : {
                'day'   : 25.9,
                'night' : 28.73,
                'eve'   : 27.75,
                'morn'  : 26.48,
            },
            'pressure'   : 1013,
            'humidity'   : 87,
            'dew_point'  : 23.49,
            'wind_speed' : 7.5,
            'wind_deg'   : 82,
            'weather'    : [
                {
                    'id'          : 502,
                    'main'        : 'Rain',
                    'description' : 'heavy intensity rain',
                    'icon'        : '10d',
                },
            ],
            'clouds'     : 100,
            'pop'        : 0.88,
            'rain'       : 42.06,
            'uvi'        : 10.89,
        },
    ]
};

nock.disableNetConnect();

nock('https://api.openweathermap.org')
    .get('/data/2.5/onecall')
    .query({
        lat     : latitude,
        lon     : longitude,
        exclude : 'minutely,alerts',
        units   : 'metric',
        appid   : apiKey,
        lang    : locale,
    })
    .reply(200, weatherResponse);

describe('OpenWeatherMapApiClient', () => {
    it('getWeather', async () => {
        const weather = await OpenWeatherMapApiClient.getWeather(latitude, longitude, days, hours, apiKey, locale);

        expect(weather.currently.temperature).toEqual(28.01);
        expect(weather.hourly[0].temperature).toEqual(28.01);
        expect(weather.daily[0].temperatureHigh).toEqual(28.25);
    });
});
